services:
  node-red:
    build: ./node-red
    depends_on:
      - bcg
      - mosquitto
      - mongodb
    environment:
      NODE_ENV: production
      TZ: ${TZ:-Europe/Prague}
      FLOWS: /data/flows/flows.json
      BACKEND_URL: ${BACKEND_URL:-http://host.docker.internal:3000}
    secrets:
      - terminal_api_key
    ports:
      - 1881:1880
    volumes:
      - ./node-red/flows:/data/flows
  bcg:
    build: ./bcg
    depends_on:
      - mosquitto
    devices:
      - "/dev/ttyUSB0:/dev/ttyUSB0"
  mosquitto:
    build: ./mosquitto
  mongodb:
    image: mongo
    volumes:
      - mongodb:/data/db
    ports:
      - 27018:27017

volumes:
  mongodb:

secrets:
  terminal_api_key:
    file: ./terminal_api_key.txt
